import Head from 'next/head';
import styles from '../styles/Home.module.css';
import Image from 'next/image';

import Banner from '../components/Banner';
import Card from '../components/Card';

export default function Home() {
  const handleOnBannerButtonClick = () => {
    console.log('clicked Banner');
  };
  return (
    <div className={styles.container}>
      <Head>
        <title>Coffee Connoisseur</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <main className={styles.main}>
        <Banner
          buttonText='View stores nearby'
          handleOnClick={handleOnBannerButtonClick}
        />
        <div className={styles.heroImage}>
          <Image
            alt='coffee beans in circle around a coffee maker'
            src='/static/hero-image.png'
            width={700}
            height={400}
          />
        </div>
        <Card
          name={'DarkHorse Coffee'}
          imgUrl='/static/hero-image.png'
          href='/coffee-store/darkhorse-coffee'
        />
      </main>
    </div>
  );
}
